/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.home;

import com.databaseCon.MotorPH_DB;
import java.awt.Color;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.security.SecureRandom;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

public class MotorPH_ForgotPassword extends javax.swing.JFrame{
    private final String email;
    private Connection connection;
    private String generatedCode;
    int otpLength = 6; // You can adjust the OTP length as needed
    String generatedOTP = SecurityCodeGenerator.generateSecurityCode(otpLength);
    String userInput = "";
    

  
   
    public MotorPH_ForgotPassword(String email, Connection connection)
    {
        initComponents();
        this.email = email;
        this.connection = connection;
         NewPass.setEditable(false);
    ConfirmPass.setEditable(false);
    otpGeneratedText.setVisible(false);
    Save.setEnabled(false);
    
    }
  
public class SecurityCodeGenerator {
    
   public static String generateSecurityCode(int length){
       
       String characters = "0123456789";
       StringBuilder otp = new StringBuilder();
       SecureRandom random = new SecureRandom();
       for(int i = 0; i < length; i++){
           int index = random.nextInt(characters.length());
           otp.append(characters.charAt(index));
       }
       return otp.toString();
    }
   
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jLabel73 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jLabel82 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        Save = new javax.swing.JButton();
        NewPass = new javax.swing.JPasswordField();
        otpGeneratedText = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        ConfirmPass = new javax.swing.JPasswordField();
        btnBack = new javax.swing.JButton();
        GenerateOTP = new javax.swing.JButton();
        VerifyOTP = new javax.swing.JButton();
        jTextFieldOtp = new javax.swing.JTextField();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel26.setBackground(new java.awt.Color(0, 0, 0));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel73.setForeground(new java.awt.Color(255, 255, 255));
        jPanel26.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 250, 80));

        jPanel25.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 100));

        jPanel27.setBackground(new java.awt.Color(0, 0, 0));
        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel74.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(255, 255, 255));
        jLabel74.setText("Subject: MO-IT101 - Computer Programming 1");
        jPanel27.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 70, -1, 20));

        jLabel75.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(255, 255, 255));
        jLabel75.setText("Office Hours: 8:00AM - 5:00PM");
        jPanel27.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 20));

        jLabel76.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(255, 255, 255));
        jLabel76.setText("Office Address: 5th Flr., The World Center #330 Sen. Gil Puyat Ave., Makati City, Manila, Philippines");
        jPanel27.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 20));

        jLabel77.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(255, 255, 255));
        jLabel77.setText("Office Phone Number: +63-2-754-7000");
        jPanel27.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        jLabel78.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(255, 255, 255));
        jLabel78.setText("Office Email: support@motorph.com");
        jPanel27.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 20));

        jLabel79.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(255, 255, 255));
        jLabel79.setText("Section: A1101");
        jPanel27.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 40, -1, 30));

        jLabel80.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(255, 255, 255));
        jLabel80.setText("Group 1");
        jPanel27.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 20, -1, 20));

        jPanel25.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 1024, 100));
        jPanel25.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 560, 340));

        jPanel28.setBackground(new java.awt.Color(255, 255, 255));
        jPanel28.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel82.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel82.setText("Welcome!");
        jPanel28.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 140, -1));

        jLabel84.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel84.setText("OTP:");
        jPanel28.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        Save.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jPanel28.add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        NewPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewPassActionPerformed(evt);
            }
        });
        jPanel28.add(NewPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 230, -1));

        otpGeneratedText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        otpGeneratedText.setText("123456");
        jPanel28.add(otpGeneratedText, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel86.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel86.setText("Confirm New Password");
        jPanel28.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        ConfirmPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmPassActionPerformed(evt);
            }
        });
        jPanel28.add(ConfirmPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 230, -1));

        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel28.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        GenerateOTP.setText("Generate");
        GenerateOTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateOTPActionPerformed(evt);
            }
        });
        jPanel28.add(GenerateOTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        VerifyOTP.setText("Verify");
        VerifyOTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerifyOTPActionPerformed(evt);
            }
        });
        jPanel28.add(VerifyOTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 80, -1));

        jTextFieldOtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOtpActionPerformed(evt);
            }
        });
        jPanel28.add(jTextFieldOtp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 150, -1));

        jLabel87.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel87.setText("New Password");
        jPanel28.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel88.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel88.setText("OTP: ");
        jPanel28.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jPanel25.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 340, 340));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        MotorPH_LoginFrame loginFrame = new MotorPH_LoginFrame();
        String newPassword = new String(NewPass.getPassword());
        String confirmPassword = new String(ConfirmPass.getPassword());
        
        try {
        connection = MotorPH_DB.getConnection();
        String query = "select * from motorphemployees.emp_msdb where Email = '"+email+"'";
        PreparedStatement preparedStatement = connection.prepareStatement(query);
        Statement st = MotorPH_DB.getConnection().createStatement();
        ResultSet rs = st.executeQuery(query);
        MotorPH_NewPassword motorPHNewPassword = new MotorPH_NewPassword(email, connection);
                // Check if new password matches confirm password
             if(newPassword.isEmpty() && confirmPassword.isEmpty()){
                 JOptionPane.showMessageDialog(this, "Please enter a password.");
             }
             else if (newPassword.equals(confirmPassword))
            {
                motorPHNewPassword.updatePassword(email, newPassword);

                JOptionPane.showMessageDialog(this, "Password changed successfully!");
                loginFrame.show();
                this.dispose();
            } else
            {
                JOptionPane.showMessageDialog(this, "New password and confirm password do not match.");
            }
        } catch (Exception ex)
        {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error updating password: " + ex.getMessage());
    }//GEN-LAST:event_SaveActionPerformed
    } 

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        MotorPH_LoginFrame loginObj = new MotorPH_LoginFrame();
        loginObj.show();
    }//GEN-LAST:event_btnBackActionPerformed

    
    private void GenerateOTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateOTPActionPerformed
        // TODO add your handling code here:
        // Generate and display the security code
        generatedCode = SecurityCodeGenerator.generateSecurityCode(otpLength);
        otpGeneratedText.setVisible(true);
        otpGeneratedText.setText(generatedCode);
        jTextFieldOtp.setText("");
    }//GEN-LAST:event_GenerateOTPActionPerformed

    private void jTextFieldOtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOtpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldOtpActionPerformed

    private void VerifyOTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerifyOTPActionPerformed
       //MotorPH_NewPassword motorPHNewPassword = new MotorPH_NewPassword(email, connection);
              // Generate and store the security code
              
               userInput = jTextFieldOtp.getText();
 // Simulate user input
           if(userInput.equals(generatedCode)){
        NewPass.setEditable(true);
        ConfirmPass.setEditable(true);
        otpGeneratedText.setVisible(true);
        otpGeneratedText.setText("Verified OTP Please create a new password!");
        jTextFieldOtp.setEditable(false);
        GenerateOTP.setEnabled(false);
        jTextFieldOtp.setBackground(Color.green);
        Save.setEnabled(true);
       }else{
        NewPass.setEditable(false);
        ConfirmPass.setEditable(false);
        otpGeneratedText.setText("Generate again!");
        jTextFieldOtp.setText("");
        GenerateOTP.setEnabled(true);
        Save.setEnabled(false);
       }
    }//GEN-LAST:event_VerifyOTPActionPerformed

    private void NewPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewPassActionPerformed

    }//GEN-LAST:event_NewPassActionPerformed

    private void ConfirmPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmPassActionPerformed

    }//GEN-LAST:event_ConfirmPassActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    { 
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MotorPH_ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MotorPH_ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MotorPH_ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MotorPH_ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MotorPH_ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            String email = "";
            Connection connection;
            public void run()
            {
                new MotorPH_ForgotPassword(email, connection).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ConfirmPass;
    private javax.swing.JButton GenerateOTP;
    private javax.swing.JPasswordField NewPass;
    private javax.swing.JButton Save;
    private javax.swing.JButton VerifyOTP;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JTextField jTextFieldOtp;
    private javax.swing.JLabel otpGeneratedText;
    // End of variables declaration//GEN-END:variables

}